# Configuration for track-playlist embedding training

# Data paths
data:
  raw_data_path: "/home/romain/Documents/Personal/Projects/Soundtrack_ML/soundtrack-ml/smart_shuffle/data/raw/track_playlist"
  processed_data_path: "/home/romain/Documents/Personal/Projects/Soundtrack_ML/soundtrack-ml/smart_shuffle/data/processed/track_playlist"
  ml_train_data_path: "/home/romain/Documents/Personal/Projects/Soundtrack_ML/soundtrack-ml/smart_shuffle/data/processed/track_playlist/playlist_sentences.pkl"
  model_save_path: "/home/romain/Documents/Personal/Projects/Soundtrack_ML/soundtrack-ml/smart_shuffle/models/track_playlist"
  model_name: "spotify_w2v.model"

# Data transformation settings
data_transform:
  max_files: 100  # Number of playlist files to process

# Word2Vec model parameters
model:
  vector_size: 256  # Dimensionality of word vectors
  window: 5  # Maximum distance between current and predicted word
  min_count: 5  # Ignores words with frequency lower than this
  workers: 4  # Number of worker threads
  epochs: 5  # Number of training epochs
  sg: 0  # Training algorithm: 0 for CBOW, 1 for skip-gram

qdrant:
  url: "https://3ed0dfdc-3f3f-4424-9123-87025b9842df.us-east4-0.gcp.cloud.qdrant.io"
  api_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.cnfVaM94fTBzg_LyAnq_Ip1mGLX7WlCy44QqoJNJhzY"
  collection_name: "track_playlist_embeddings"
